import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navLinks = [
  { href: "/", label: "Chat" },
  { href: "/product-images", label: "画像ベクトル化" },
  { href: "/product-images-gemini", label: "画像ベクトル化(Gemini)" },
  { href: "/product-images-openai", label: "画像ベクトル化(OpenAI)" },
  { href: "/product-images-vectorize", label: "画像ベクトル化(独自API)" },
  { href: "/product-images-vectorize/list", label: "ベクトル一覧(独自API)" },
  { href: "/product-images-vectorize/search", label: "画像検索(独自API)" },
  { href: "/image-search", label: "画像検索(アップロード)" },
  { href: "/text-registration", label: "文字情報登録" },
  { href: "/product-images/list", label: "ベクトル一覧" },
  { href: "/playing-with-neon", label: "playing_with_neon" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="border-b bg-background/80 backdrop-blur">
          <div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-3 sm:px-6 lg:px-8">
            <div className="flex items-center gap-2 text-sm font-semibold">
              <span className="rounded bg-primary/10 px-2 py-1 text-primary">
                AI Chat App
              </span>
              <span className="text-muted-foreground">Neon + AI</span>
            </div>
            <nav className="flex items-center gap-3 text-sm text-muted-foreground md:hidden">
              {navLinks.map((link) => (
                <Link className="hover:text-foreground" href={link.href} key={link.href}>
                  {link.label}
                </Link>
              ))}
            </nav>
          </div>
        </header>
        <div className="mx-auto flex max-w-6xl gap-6 px-4 py-6 sm:px-6 lg:px-8">
          <aside className="sticky top-6 hidden h-fit w-60 flex-col gap-2 rounded-lg border bg-card/60 p-4 text-sm text-muted-foreground md:flex">
            <div className="text-xs font-semibold uppercase tracking-[0.2em] text-muted-foreground">
              Navigation
            </div>
            <nav className="flex flex-col gap-1">
              {navLinks.map((link) => (
                <Link
                  className="rounded px-2 py-1 hover:bg-muted/60 hover:text-foreground"
                  href={link.href}
                  key={link.href}
                >
                  {link.label}
                </Link>
              ))}
            </nav>
          </aside>
          <main className="min-w-0 flex-1">{children}</main>
        </div>
      </body>
    </html>
  );
}
